"""empty message

Revision ID: e27c68118dd3
Revises: c331e4aa1ca9
Create Date: 2023-06-27 11:01:40.474869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27c68118dd3'
down_revision = 'c331e4aa1ca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
