"""empty message

Revision ID: ec14baf95d9c
Revises: f62c42464809
Create Date: 2023-06-26 15:53:46.805200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec14baf95d9c'
down_revision = 'f62c42464809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
